// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-tH9u-yXhzZEeAeBeagEDsY6vaacREb0',
    appId: '1:375118321042:web:a69fede1291e1c97df9d4b',
    messagingSenderId: '375118321042',
    projectId: 'fire-auth-458f1',
    authDomain: 'fire-auth-458f1.firebaseapp.com',
    storageBucket: 'fire-auth-458f1.firebasestorage.app',
    measurementId: 'G-8F8Y9914SM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaSSKnGSHRpN-MLF2WJYdprwXHjqAEUhk',
    appId: '1:375118321042:android:a9ba30518db96df4df9d4b',
    messagingSenderId: '375118321042',
    projectId: 'fire-auth-458f1',
    storageBucket: 'fire-auth-458f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPWDvUE6p4fFAy9NHQ1x32v0Ng01t5Z2M',
    appId: '1:375118321042:ios:58e49622ac39224fdf9d4b',
    messagingSenderId: '375118321042',
    projectId: 'fire-auth-458f1',
    storageBucket: 'fire-auth-458f1.firebasestorage.app',
    iosBundleId: 'com.allievo.timagraios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPWDvUE6p4fFAy9NHQ1x32v0Ng01t5Z2M',
    appId: '1:375118321042:ios:6845f77cb1544e52df9d4b',
    messagingSenderId: '375118321042',
    projectId: 'fire-auth-458f1',
    storageBucket: 'fire-auth-458f1.firebasestorage.app',
    iosBundleId: 'com.example.timagraNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-tH9u-yXhzZEeAeBeagEDsY6vaacREb0',
    appId: '1:375118321042:web:97452d2ac0d86ffedf9d4b',
    messagingSenderId: '375118321042',
    projectId: 'fire-auth-458f1',
    authDomain: 'fire-auth-458f1.firebaseapp.com',
    storageBucket: 'fire-auth-458f1.firebasestorage.app',
    measurementId: 'G-9FJLC2WBZW',
  );
}
